#!/bin/bash

scriptName=$(basename $0)

function Maven() {
  mvn --quiet "$@"
}

function Ant() {
  ant "$@"
}

function All() {
  Build && Run
}

function Build() {
  Ant war
}

function Run() {
  Maven jetty:deploy-war
}

function Clean() {
  Ant clean
  Maven clean
}

function Usage() {
  echo "Usage: $scriptName [all | build | run | clean] …" >&2
  exit 2
}

function ProcessArg() {
  case $1 in
    all) All;;
    build) Build;;
    run)   Run;;
    clean) Clean;;
  esac
}

while getopts ":h" flag; do
  case $flag in
    h) Usage;;
    \?) [[ $OPTARG != '?' ]] && echo "$scriptName: invalid option -- $OPTARG" >&2; Usage;;
  esac
done

if [[ $# -eq 0 ]]; then
  ProcessArg all
else
  for arg in "$@"; do
    ProcessArg $arg || exit $?
  done
fi
